openapi: 3.1.0
info:
  title: "My API"
  version: "1.0.0"
  description: "reproduce redocly cli split issue"
paths:
  /:
    get:
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
                    example: "Hello, world!"
        '400':
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Error:
      type: "object"
      properties:
        message:
          type: "string"
          example: "An error occurred"